$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: eda
display_name: eda
is_deterministic: False
command: >-
  python eda.py
  --datasets-pkl ${{inputs.datasets_pkl}}
  --runinfo ${{inputs.runinfo}}
  --trainlog ${{inputs.trainlog}}
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/dashboard
environment: azureml:ltcfthvenv@latest
inputs:
  datasets_pkl:
    type: path
  runinfo:
    type: path
  trainlog:
    type: path
outputs:
  transformed_data:
    type: path
