$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: models
display_name: models
is_deterministic: False
command: >-
  python models.py
  --transformed-data ${{outputs.transformed_data}}
code: ../../src/pipeline/dashboard
environment: azureml:ltcfthvenv@latest
outputs:
  transformed_data:
    type: path
